Implemented user/conversation/message deletion
ataylor4/codeu_project_2017 pull request #5
Opened 2017-04-04 04:27 UTC by alxchen

on clientside for command line, excluding Stores

2017-04-04 04:31 UTC, ataylor4 requested changes
Add unit tests and minor nitpicks, otherwise LGTM

2017-04-04 04:31 UTC, ataylor4 commented on src/codeu/chat/client/ClientConversation.java
> +    //summariesSortedByTitle.remove(cs.title); // Need to update with BTree store
should be summariesSortedByTitle = summariesSortedByTitle.remove(cs.title)

2017-04-04 04:31 UTC, ataylor4 commented on src/codeu/chat/client/ClientConversation.java
> +
np: extra newline

2017-04-04 04:31 UTC, ataylor4 commented on src/codeu/chat/client/commandline/Chat.java
> +  private void removeUser(String name) { clientContext.user.removeUser(name);}
should be whitespace

2017-04-22 05:57 UTC, rkinini approved these changes
lgtm

2017-04-22 06:21 UTC, merged